./font-patcher -l --powerline --powerlineextra --fontawesome --fontawesomeextension --fontlogos --octicons ./sarasa/sarasa-mono-tc-bold.ttf
./font-patcher -l --powerline --powerlineextra --fontawesome --fontawesomeextension --fontlogos --octicons ./sarasa/sarasa-mono-tc-bolditalic.ttf
./font-patcher -l --powerline --powerlineextra --fontawesome --fontawesomeextension --fontlogos --octicons ./sarasa/sarasa-mono-tc-extralight.ttf
./font-patcher -l --powerline --powerlineextra --fontawesome --fontawesomeextension --fontlogos --octicons ./sarasa/sarasa-mono-tc-extralightitalic.ttf
./font-patcher -l --powerline --powerlineextra --fontawesome --fontawesomeextension --fontlogos --octicons ./sarasa/sarasa-mono-tc-italic.ttf
./font-patcher -l --powerline --powerlineextra --fontawesome --fontawesomeextension --fontlogos --octicons ./sarasa/sarasa-mono-tc-light.ttf
./font-patcher -l --powerline --powerlineextra --fontawesome --fontawesomeextension --fontlogos --octicons ./sarasa/sarasa-mono-tc-lightitalic.ttf
./font-patcher -l --powerline --powerlineextra --fontawesome --fontawesomeextension --fontlogos --octicons ./sarasa/sarasa-mono-tc-regular.ttf
./font-patcher -l --powerline --powerlineextra --fontawesome --fontawesomeextension --fontlogos --octicons ./sarasa/sarasa-mono-tc-semibold.ttf
./font-patcher -l --powerline --powerlineextra --fontawesome --fontawesomeextension --fontlogos --octicons ./sarasa/sarasa-mono-tc-semibolditalic.ttf
